### ISSUE TITLE
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True.

### ISSUE THREAD

**Issue by FaSoLaSiDoFa** [ruoqiu6/chat-with-Elysia#1]
大佬，我按照流程操作，运行后网页也自动弹出，然后就报错了
请问下应该怎么解决？

Traceback (most recent call last):
  File "E:\AI\chat-with-Elysia-master\main.py", line 31, in <module>
    app.launch(share=args.share)   #args.share
  File "E:\AI\chat-with-Elysia-master\gradio\blocks.py", line 1444, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True.

然后我把app.launch(share=args.share)改成app.launch(share=True) 后报错：

Traceback (most recent call last):
  File "E:\AI\chat-with-Elysia-master\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "E:\AI\chat-with-Elysia-master\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "E:\AI\chat-with-Elysia-master\urllib3\connection.py", line 374, in connect
    self._tunnel()
  File "C:\Users\1\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 929, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 500 Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AI\chat-with-Elysia-master\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "E:\AI\chat-with-Elysia-master\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "E:\AI\chat-with-Elysia-master\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.gradio.app', port=443): Max retries exceeded with url: /v2/tunnel-request (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Internal Server Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AI\chat-with-Elysia-master\main.py", line 31, in <module>
    app.launch(share=True)   #args.share
  File "E:\AI\chat-with-Elysia-master\gradio\blocks.py", line 1472, in launch
    self.share_url = networking.setup_tunnel(
  File "E:\AI\chat-with-Elysia-master\gradio\networking.py", line 160, in setup_tunnel
    response = requests.get(GRADIO_API_SERVER)
  File "E:\AI\chat-with-Elysia-master\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "E:\AI\chat-with-Elysia-master\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\AI\chat-with-Elysia-master\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\AI\chat-with-Elysia-master\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\AI\chat-with-Elysia-master\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.gradio.app', port=443): Max retries exceeded with url: /v2/tunnel-request (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Internal Server Error')))

**Comment by URfatherTHERE** [comment]
我遇到了同样的问题，通过pip install orjson -i https://pypi.tuna.tsinghua.edu.cn/simple/安装最新的orjson这个库，再把main.py的   31行改成这个app.launch(share=True)，然后就能正常启动了

**Comment by FaSoLaSiDoFa** [comment]
> 我遇到了同样的问题，通过pip install orjson -i [https://pypi.tuna.tsinghua.edu.cn/simple/安装最新的orjson这个库，再把main.py的](https://pypi.tuna.tsinghua.edu.cn/simple/%E5%AE%89%E8%A3%85%E6%9C%80%E6%96%B0%E7%9A%84orjson%E8%BF%99%E4%B8%AA%E5%BA%93%EF%BC%8C%E5%86%8D%E6%8A%8Amain.py%E7%9A%84) 31行改成这个app.launch(share=True)，然后就能正常启动了

我卸载orjson再重装，改成这个app.launch(share=True)后，报错：
Traceback (most recent call last):
  File "E:\AI\chat-with-Elysia-master\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "E:\AI\chat-with-Elysia-master\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "E:\AI\chat-with-Elysia-master\urllib3\connection.py", line 374, in connect
    self._tunnel()
  File "C:\Users\1\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 929, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 500 Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AI\chat-with-Elysia-master\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "E:\AI\chat-with-Elysia-master\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "E:\AI\chat-with-Elysia-master\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.gradio.app', port=443): Max retries exceeded with url: /v2/tunnel-request (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Internal Server Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\AI\chat-with-Elysia-master\main.py", line 31, in <module>
    app.launch(share=True)   #args.share
  File "E:\AI\chat-with-Elysia-master\gradio\blocks.py", line 1472, in launch
    self.share_url = networking.setup_tunnel(
  File "E:\AI\chat-with-Elysia-master\gradio\networking.py", line 160, in setup_tunnel
    response = requests.get(GRADIO_API_SERVER)
  File "E:\AI\chat-with-Elysia-master\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "E:\AI\chat-with-Elysia-master\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\AI\chat-with-Elysia-master\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\AI\chat-with-Elysia-master\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "E:\AI\chat-with-Elysia-master\requests\adapters.py", line 559, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.gradio.app', port=443): Max retries exceeded with url: /v2/tunnel-request (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 500 Internal Server Error')))

**Comment by FaSoLaSiDoFa** [comment]
> 
config.json中是这样设置的
    "proxy" : "127.0.0.1:",
    "model" : "gpt-3.5-turbo",
    "store-path" : "./data",

**Comment by FaSoLaSiDoFa** [comment]
> 
config.json中是这样设置的
    "proxy" : "127.0.0.1:",
    "model" : "gpt-3.5-turbo",
    "store-path" : "./data",

**Comment by FaSoLaSiDoFa** [comment]
> 
config.json中是这样设置的
    "proxy" : "127.0.0.1:",
    "model" : "gpt-3.5-turbo",
    "store-path" : "./data",

**Comment by FaSoLaSiDoFa** [comment]
C:\Users\1>ping api.gradio.app

正在 Ping api.gradio.app [198.18.0.106] 具有 32 字节的数据:
来自 198.18.0.106 的回复: 字节=32 时间=488ms TTL=64
来自 198.18.0.106 的回复: 字节=32 时间<1ms TTL=64
来自 198.18.0.106 的回复: 字节=32 时间<1ms TTL=64
来自 198.18.0.106 的回复: 字节=32 时间=1ms TTL=64

198.18.0.106 的 Ping 统计信息:
    数据包: 已发送 = 4，已接收 = 4，丢失 = 0 (0% 丢失)，
往返行程的估计时间(以毫秒为单位):
    最短 = 0ms，最长 = 488ms，平均 = 122ms

**Comment by URfatherTHERE** [comment]
> 

proxy后面需要加上端口，我用的clsah  是这样设置的，   "proxy" : "127.0.0.1:7890",

**Comment by URfatherTHERE** [comment]
我在这里在补充一下我启动成功之前安装的依赖吧，python3.8环境。
pip install matplotlib -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install ffmpy -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install markdown-it-py -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install mdit-py-plugins -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install pandas -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install pycrypto -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install pycryptodome -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install fsspec -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install pydub -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install -U websockets -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install uvicorn -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install fastapi -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install aiofiles -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install pyaudio -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install scipy -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install joblib -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install decorator -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install numba -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install pooch -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install SoundFile -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install audioread -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install resampy -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install torch -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install unidecode -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install jamo -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install python-multipart -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install orjson -i https://pypi.tuna.tsinghua.edu.cn/simple/

**Comment by FaSoLaSiDoFa** [comment]
我是Python 3.9，我把clsah更新了，配置里的端口也加上了，又把这些依赖重新装了一遍，现在运行到网页里点击“生成对话”后报错：
Traceback (most recent call last):
  File "E:\AI\chat-with-Elysia-master\gradio\routes.py", line 374, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\AI\chat-with-Elysia-master\gradio\blocks.py", line 1017, in process_api
    result = await self.call_function(
  File "E:\AI\chat-with-Elysia-master\gradio\blocks.py", line 835, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\1\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\1\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\1\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\AI\chat-with-Elysia-master\parse.py", line 62, in PipeChat
    return self.switchAudio(self.getText(text))
  File "E:\AI\chat-with-Elysia-master\parse.py", line 39, in switchAudio
    generateSound(text, audio_path)
  File "E:\AI\chat-with-Elysia-master\soundMaker.py", line 61, in generateSound
    len(hps_ms.symbols),
AttributeError: 'HParams' object has no attribute 'symbols'

**Comment by URfatherTHERE** [comment]
> 我是Python 3.9，我把clsah更新了，配置里的端口也加上了，又把这些依赖重新装了一遍，现在运行到网页里点击“生成对话”后报错： Traceback (most recent call last): File "E:\AI\chat-with-Elysia-master\gradio\routes.py", line 374, in run_predict output = await app.get_blocks().process_api( File "E:\AI\chat-with-Elysia-master\gradio\blocks.py", line 1017, in process_api result = await self.call_function( File "E:\AI\chat-with-Elysia-master\gradio\blocks.py", line 835, in call_function prediction = await anyio.to_thread.run_sync( File "C:\Users\1\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\to_thread.py", line 31, in run_sync return await get_asynclib().run_sync_in_worker_thread( File "C:\Users\1\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio_backends_asyncio.py", line 937, in run_sync_in_worker_thread return await future File "C:\Users\1\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio_backends_asyncio.py", line 867, in run result = context.run(func, *args) File "E:\AI\chat-with-Elysia-master\parse.py", line 62, in PipeChat return self.switchAudio(self.getText(text)) File "E:\AI\chat-with-Elysia-master\parse.py", line 39, in switchAudio generateSound(text, audio_path) File "E:\AI\chat-with-Elysia-master\soundMaker.py", line 61, in generateSound len(hps_ms.symbols), AttributeError: 'HParams' object has no attribute 'symbols'

看着还是像配置文件的问题，方便看下配置文件吗
